-- Doka Cloud Edition — D1 metadata baseline.
-- Object bytes stay in Storj; embeddings stay in Vectorize.
-- IDs are generated by the API as UUID strings. Timestamps are UTC ISO-8601 text.
-- This migration is intentionally not bound/applied to the production Worker yet.

CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE COLLATE NOCASE,
    display_name TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled', 'deleted')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE organizations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
    created_by TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE organization_members (
    organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (organization_id, user_id)
);

CREATE INDEX organization_members_user_idx
    ON organization_members(user_id, organization_id);

CREATE TABLE documents (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    organization_id TEXT REFERENCES organizations(id) ON DELETE SET NULL,
    object_key TEXT NOT NULL UNIQUE
        CHECK (length(object_key) BETWEEN 1 AND 1024
            AND substr(object_key, 1, 1) <> '/'
            AND instr(object_key, '..') = 0),
    filename TEXT NOT NULL CHECK (length(trim(filename)) BETWEEN 1 AND 255),
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream'
        CHECK (length(content_type) BETWEEN 1 AND 255),
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (
        length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-fA-F]*'
    ),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'review', 'quarantined', 'archived')),
    metadata_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(metadata_json)),
    folder_path TEXT NOT NULL DEFAULT '/'
        CHECK (
            folder_path = '/' OR (
                substr(folder_path, 1, 1) = '/'
                AND substr(folder_path, -1, 1) <> '/'
                AND instr(folder_path, '..') = 0
            )
        ),
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX documents_owner_created_idx
    ON documents(owner_id, created_at DESC);
CREATE INDEX documents_org_deleted_created_idx
    ON documents(organization_id, deleted_at, created_at DESC);
CREATE INDEX documents_owner_status_idx
    ON documents(owner_id, status, deleted_at);
CREATE INDEX documents_owner_folder_idx
    ON documents(owner_id, folder_path, deleted_at);

CREATE TABLE document_versions (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL CHECK (version_no > 0),
    object_key TEXT NOT NULL UNIQUE
        CHECK (length(object_key) BETWEEN 1 AND 1024
            AND substr(object_key, 1, 1) <> '/'
            AND instr(object_key, '..') = 0),
    filename TEXT NOT NULL CHECK (length(trim(filename)) BETWEEN 1 AND 255),
    content_type TEXT NOT NULL DEFAULT 'application/octet-stream'
        CHECK (length(content_type) BETWEEN 1 AND 255),
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    sha256 TEXT NOT NULL CHECK (
        length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-fA-F]*'
    ),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE(document_id, version_no)
);

CREATE INDEX document_versions_document_created_idx
    ON document_versions(document_id, version_no DESC);

CREATE TABLE document_permissions (
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission TEXT NOT NULL CHECK (permission IN ('read', 'write', 'admin')),
    granted_by TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (document_id, user_id)
);

CREATE INDEX document_permissions_user_idx
    ON document_permissions(user_id, document_id);

CREATE TABLE document_chunks (
    id TEXT PRIMARY KEY,
    document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    version_id TEXT NOT NULL REFERENCES document_versions(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    content TEXT NOT NULL,
    content_sha256 TEXT NOT NULL CHECK (
        length(content_sha256) = 64
        AND content_sha256 NOT GLOB '*[^0-9a-fA-F]*'
    ),
    vector_id TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(metadata_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE(document_id, version_id, chunk_index)
);

CREATE INDEX document_chunks_document_idx
    ON document_chunks(document_id, version_id, chunk_index);

-- A chunk must always belong to a version of the same document.
CREATE TRIGGER document_chunks_version_matches_document_insert
BEFORE INSERT ON document_chunks
WHEN NOT EXISTS (
    SELECT 1 FROM document_versions
    WHERE id = NEW.version_id AND document_id = NEW.document_id
)
BEGIN
    SELECT RAISE(ABORT, 'document chunk version mismatch');
END;

CREATE TRIGGER document_chunks_version_matches_document_update
BEFORE UPDATE OF document_id, version_id ON document_chunks
WHEN NOT EXISTS (
    SELECT 1 FROM document_versions
    WHERE id = NEW.version_id AND document_id = NEW.document_id
)
BEGIN
    SELECT RAISE(ABORT, 'document chunk version mismatch');
END;

CREATE TABLE audit_events (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    -- Historical identifier intentionally has no FK so hard deletion cannot rewrite audit history.
    document_id TEXT,
    action TEXT NOT NULL CHECK (action IN (
        'upload', 'download', 'preview', 'update', 'trash', 'restore',
        'permanent_delete', 'version_create', 'version_restore'
    )),
    filename TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}'
        CHECK (json_valid(metadata_json)),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX audit_events_owner_created_idx
    ON audit_events(owner_id, created_at DESC);
CREATE INDEX audit_events_document_created_idx
    ON audit_events(document_id, created_at DESC);

-- Audit history is append-only; privileged retention is a separate controlled operation.
CREATE TRIGGER audit_events_no_update
BEFORE UPDATE ON audit_events
BEGIN
    SELECT RAISE(ABORT, 'audit events are append-only');
END;

CREATE TRIGGER audit_events_no_delete
BEFORE DELETE ON audit_events
BEGIN
    SELECT RAISE(ABORT, 'audit events are append-only');
END;

CREATE TABLE jobs (
    id TEXT PRIMARY KEY,
    organization_id TEXT REFERENCES organizations(id) ON DELETE SET NULL,
    job_type TEXT NOT NULL CHECK (length(trim(job_type)) BETWEEN 1 AND 100),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'succeeded', 'failed', 'dead')),
    idempotency_key TEXT NOT NULL UNIQUE CHECK (length(idempotency_key) BETWEEN 1 AND 255),
    payload_json TEXT NOT NULL CHECK (json_valid(payload_json)),
    result_json TEXT CHECK (result_json IS NULL OR json_valid(result_json)),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts BETWEEN 1 AND 20),
    available_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_error TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX jobs_status_available_idx ON jobs(status, available_at);

-- D1 is authoritative. A source mutation and its outbox event must be written in
-- the same D1 batch; a QStash consumer applies each event idempotently to Turso.
CREATE TABLE outbox_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL CHECK (length(trim(event_type)) BETWEEN 1 AND 120),
    aggregate_type TEXT NOT NULL CHECK (length(trim(aggregate_type)) BETWEEN 1 AND 80),
    aggregate_id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL UNIQUE CHECK (length(idempotency_key) BETWEEN 1 AND 255),
    payload_json TEXT NOT NULL CHECK (json_valid(payload_json)),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'delivered', 'dead')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INTEGER NOT NULL DEFAULT 8 CHECK (max_attempts BETWEEN 1 AND 20),
    available_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    lease_until TEXT,
    lease_token TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    delivered_at TEXT,
    last_error TEXT
);

CREATE INDEX outbox_events_pending_idx
    ON outbox_events(status, available_at, created_at);
